# Stage 1: Build Golang executable
FROM golang:1.20.5-alpine3.18 AS builder
WORKDIR /app

COPY ./sandboxes .

RUN go mod download

RUN go build -o runner ./python/sandbox.go


FROM python:3.10-alpine3.18
WORKDIR /app

COPY --from=builder /app/runner .

CMD ["./runner"]
